import {BOARD_CONTENTS,BOARD_CATEGORIES,BOARD_STATUSES} from '../platform/hubBoardCatalog.js';
const e=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#39;');
const date=value=>value?new Date(value).toLocaleDateString('ko-KR'):'-';
const label=(map,key)=>map[key]||'기타';
const fileCards=(files=[],messageId=null)=>files.filter(item=>(item.message_id||null)===(messageId||null)).map(item=>`<button type="button" class="hub-board__image" data-action="hub-board-image" data-image-path="${e(item.storage_path)}" title="사진 열기: ${e(item.file_name)}">${item.signedUrl?`<img src="${e(item.signedUrl)}" alt="${e(item.file_name)}">`:`<span aria-hidden="true">▧</span>`}<span>${e(item.file_name)}</span><small>사진 보기 ↗</small></button>`).join('');
const pendingFiles=state=>(state.hubBoard?.files||[]).map(item=>`<div class="hub-board__preview"><img src="${e(item.url)}" alt="첨부 예정 사진"><button type="button" data-action="hub-board-file-remove" data-file-id="${e(item.id)}" aria-label="첨부 제거">×</button></div>`).join('');
const attach=state=>`<label class="hub-board__attach" data-hub-board-drop>＋ 사진 첨부 <input type="file" accept="image/jpeg,image/png,image/webp" multiple data-hub-board-images></label><span class="hub-board__help">JPG · PNG · WEBP / 한 장 10MB 이하 / 최대 5장 · 붙여넣기도 가능</span><div class="hub-board__previews" aria-live="polite">${pendingFiles(state)}</div>`;
const formActions=(name='등록하기')=>`<div class="hub-board__form-actions"><button type="button" class="hub-board__ghost" data-action="hub-board-cancel">취소</button><button type="submit" class="hub-board__primary">${name} →</button></div>`;
export function renderHubNewsStrip(state){
 const latest=state.hubBoard?.notices?.[0];
 return `<section class="hub-news" aria-label="LAC HUB 소식과 문의"><div class="hub-news__notice"><span class="hub-news__eyebrow">LAC 소식 <i aria-hidden="true"></i></span>${latest?`<button type="button" data-action="hub-board-notice" data-notice-id="${e(latest.id)}"><strong>[공지] ${e(latest.title)}</strong><small>${date(latest.published_at)}</small></button>`:`<div class="hub-news__empty"><strong>공지사항</strong><span>${state.hubBoard?.error?'게시판 설정 확인이 필요합니다.':'새로운 소식은 이곳에서 확인하세요.'}</span></div>`}</div><div class="hub-news__actions"><button type="button" data-action="hub-board-open" class="hub-news__all">게시판 가기 <span aria-hidden="true">↗</span></button><button type="button" data-action="hub-board-compose" class="hub-news__write">문의 · 건의 작성 <span aria-hidden="true">→</span></button></div></section>`;
}
export function renderHubBoard(state){
 const board=state.hubBoard||{};const mode=board.mode||'list';const tab=board.tab||'support';
 const isAdmin=state.platformAdmin===true;
 const top=`<div class="hub-board__top"><button type="button" data-action="go-hub" class="hub-board__back">← HUB 메인</button><span>LAC HUB <b>·</b> 고객지원</span></div>`;
 const heading=`<header class="hub-board__heading"><div><span>LAC HUB SUPPORT</span><h1>공지 · 문의 · 건의</h1><p>서비스 이용 중 궁금한 점이나 개선 의견을 남겨주세요.</p></div><button type="button" class="hub-board__primary" data-action="hub-board-compose">＋ 문의 · 건의 작성</button></header>`;
 const message=board.error?`<div class="hub-board__error" role="alert">${e(board.error)}<small>최초 적용 시에는 데이터베이스에 Phase 19 게시판 SQL을 먼저 실행해야 합니다. 기존 회사 관리 게시판과 데이터는 그대로 보존됩니다.</small></div>`:'';
 const notices=(board.notices||[]);
 const ticketRows=(board.tickets||[]).filter(item=>(board.filterContent==='all'||!board.filterContent||item.content_key===board.filterContent)&&(board.filterCategory==='all'||!board.filterCategory||item.category===board.filterCategory));
 const tabs=`<nav class="hub-board__tabs" aria-label="게시판 구분"><button type="button" data-action="hub-board-tab" data-board-tab="support" class="${tab==='support'?'is-active':''}">문의 · 건의</button><button type="button" data-action="hub-board-tab" data-board-tab="notices" class="${tab==='notices'?'is-active':''}">공지사항</button></nav>`;
 const noticeList=`<section class="hub-board__list"><div class="hub-board__list-head"><strong>공지사항</strong>${isAdmin?'<button type="button" class="hub-board__ghost" data-action="hub-board-notice-compose">＋ 공지 작성</button>':''}</div>${notices.length?notices.map(item=>`<button type="button" class="hub-board__row" data-action="hub-board-notice" data-notice-id="${e(item.id)}"><span class="hub-board__pill hub-board__pill--notice">공지</span><strong>${e(item.title)}</strong><small>${date(item.published_at)}</small><span>→</span></button>`).join(''):'<p class="hub-board__empty">등록된 공지가 없습니다.</p>'}</section>`;
 const filters=`<div class="hub-board__filters"><label>콘텐츠 <select data-hub-board-filter="content"><option value="all">전체</option>${Object.entries(BOARD_CONTENTS).map(([key,value])=>`<option value="${key}" ${board.filterContent===key?'selected':''}>${value}</option>`).join('')}</select></label><label>문의 유형 <select data-hub-board-filter="category"><option value="all">전체</option>${Object.entries(BOARD_CATEGORIES).map(([key,value])=>`<option value="${key}" ${board.filterCategory===key?'selected':''}>${value}</option>`).join('')}</select></label></div>`;
 const tickets=`<section class="hub-board__list"><div class="hub-board__list-head"><div><strong>${isAdmin?'전체 문의 · 건의':'내 문의 · 건의'}</strong><small>작성자와 LAC HUB 운영자만 글과 첨부 사진을 볼 수 있습니다.</small></div>${filters}</div>${ticketRows.length?ticketRows.map(item=>`<button type="button" class="hub-board__row" data-action="hub-board-ticket" data-ticket-id="${e(item.id)}"><span class="hub-board__pill">${e(label(BOARD_CONTENTS,item.content_key))}</span><span class="hub-board__row-copy"><strong>[${e(label(BOARD_CATEGORIES,item.category))}] ${e(item.title)}</strong>${isAdmin?`<small>${e(item.author_name)}</small>`:''}</span><small>${date(item.updated_at)}</small><span class="hub-board__status">${e(label(BOARD_STATUSES,item.status))}</span><span>→</span></button>`).join(''):'<p class="hub-board__empty">해당하는 문의가 없습니다. 궁금한 점을 첫 글로 남겨보세요.</p>'}</section>`;
 let contents='';
 if(mode==='compose'){
  contents=`<section class="hub-board__sheet"><div class="hub-board__sheet-top"><span>새 글 작성</span><button type="button" data-action="hub-board-cancel">×</button></div><form data-form="hub-board-ticket" class="hub-board__form"><div class="hub-board__form-grid"><label>콘텐츠 유형<select name="content_key" required>${Object.entries(BOARD_CONTENTS).map(([key,value])=>`<option value="${key}">${value}</option>`).join('')}</select></label><label>문의 유형<select name="category" required>${Object.entries(BOARD_CATEGORIES).map(([key,value])=>`<option value="${key}">${value}</option>`).join('')}</select></label></div><label>제목<input name="title" required minlength="2" maxlength="120" placeholder="문의 내용을 짧게 요약해 주세요"></label><label>내용<textarea name="body" required minlength="2" maxlength="4000" rows="7" placeholder="상황과 확인이 필요한 부분을 자세히 적어주세요."></textarea></label>${attach(state)}<p class="hub-board__privacy">🔒 글과 사진은 작성자 본인과 LAC HUB 운영자만 확인할 수 있습니다.</p>${formActions()}</form></section>`;
 } else if(mode==='detail'){
  const ticket=board.ticket;
  contents=!ticket?'<div class="hub-board__empty">게시글을 불러오는 중입니다.</div>':`<article class="hub-board__sheet"><div class="hub-board__sheet-top"><button type="button" data-action="hub-board-cancel">← 목록으로</button>${isAdmin?`<label>처리 상태 <select data-hub-board-status data-ticket-id="${e(ticket.id)}">${Object.entries(BOARD_STATUSES).map(([key,value])=>`<option value="${key}" ${ticket.status===key?'selected':''}>${value}</option>`).join('')}</select></label>`:`<span>${e(label(BOARD_STATUSES,ticket.status))}</span>`}</div><div class="hub-board__detail-head"><span class="hub-board__pill">${e(label(BOARD_CONTENTS,ticket.content_key))}</span><span class="hub-board__pill">${e(label(BOARD_CATEGORIES,ticket.category))}</span><small>${date(ticket.created_at)}</small><h2>${e(ticket.title)}</h2><p>${e(ticket.body)}</p><div class="hub-board__attachments">${fileCards(ticket.attachments)}</div></div><div class="hub-board__messages"><h3>답변 · 추가 문의 <small>${ticket.messages?.length||0}</small></h3>${(ticket.messages||[]).map(item=>`<div class="hub-board__message ${item.is_staff?'is-staff':''}"><div><b>${e(item.is_staff?'LAC HUB 운영자':'작성자')}</b><small>${date(item.created_at)}</small></div><p>${e(item.body)}</p><div class="hub-board__attachments">${fileCards(ticket.attachments,item.id)}</div></div>`).join('')||'<p class="hub-board__empty">답변을 기다리고 있습니다.</p>'}</div><form class="hub-board__form hub-board__reply" data-form="hub-board-reply"><label>답변 작성<textarea required name="body" rows="4" maxlength="4000" placeholder="추가 설명이나 답변을 작성해 주세요."></textarea></label>${attach(state)}${formActions('답변 등록')}</form></article>`;
 } else if(mode==='notice'){
  const notice=notices.find(item=>item.id===board.noticeId);
  contents=`<article class="hub-board__sheet"><div class="hub-board__sheet-top"><button type="button" data-action="hub-board-cancel">← 공지 목록</button></div>${notice?`<div class="hub-board__detail-head"><span class="hub-board__pill hub-board__pill--notice">공지</span><small>${date(notice.published_at)}</small><h2>${e(notice.title)}</h2><p>${e(notice.body)}</p></div>`:'<p class="hub-board__empty">공지를 찾지 못했습니다.</p>'}</article>`;
 } else if(mode==='notice-compose'&&isAdmin){
  contents=`<section class="hub-board__sheet"><div class="hub-board__sheet-top">새 공지 작성<button type="button" data-action="hub-board-cancel">×</button></div><form class="hub-board__form" data-form="hub-board-notice"><label>공지 제목<input name="title" required minlength="2" maxlength="120"></label><label>공지 내용<textarea name="body" rows="8" required minlength="2" maxlength="4000"></textarea></label>${formActions('공지 등록')}</form></section>`;
 } else { contents=tabs+(tab==='notices'?noticeList:tickets); }
 return `<div class="hub-board"><main class="hub-board__container">${top}${heading}${message}${contents}${state.companies?.length?`<aside class="hub-board__legacy"><span>이전 회사 문의 기록</span><button type="button" data-page="questions">기존 질문 내역 →</button><button type="button" data-page="suggestions">기존 건의 내역 →</button></aside>`:''}<footer class="hub-board__footer">LAC HUB · 문의와 첨부파일은 작성자와 플랫폼 운영자에게만 공개됩니다.</footer></main></div>`;
}
